words = [
    "buildable",
    "CLI",
    "codespell",
    "cpp's",
    "cuda",
    "det",
    "elo",
    "Flesch",
    "gguf",
    "jsonschema",
    "Kincaid",
    "lcpp",
    "leaderboard",
    "leaderboards",
    "lfm",
    "llamacpp",
    "lms",
    "lmstudio",
    "markdownlint",
    "mise",
    "mlock",
    "MLX",
    "mmap",
    "mnt",
    "MTP",
    "Nvidia",
    "qat",
    "quants",
    "qwen",
    "rebuildable",
    "RTX",
    "tok"
]
